[package]
name = "do_traits"
keywords.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
fx = { path = "../fx" }

