name: cargo-test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v30
      - uses: actions/checkout@v4
      - run: nix develop --accept-flake-config -c cargo test
