name: fmt
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  nix-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix fmt -- --ci
